version: "3"
services:
  adforgesite:
    image: adforgesite:latest
    restart: unless-stopped
    networks:
        - container-network

networks:
  container-network:
    name: container-network
    driver: bridge